suite: test kafka-chart/charts/cp-ksql-server/templates/external-service.yaml
templates:
  - external-service.yaml
tests:
  - it: should pass
    release:
      name: demo-release
    asserts:
      - equal: 
          path: apiVersion
          value: [NeedYourInput]
      - equal: 
          path: kind
          value: [NeedYourInput]
      - equal: 
          path: metadata.name
          value: [NeedYourInput]
      - equal: 
          path: metadata.annotations
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.app
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.chart
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.release
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.heritage
          value: [NeedYourInput]
      - equal: 
          path: spec.type
          value: [NeedYourInput]
      - equal: 
          path: spec.externalTrafficPolicy
          value: [NeedYourInput]
      - equal: 
          path: spec.loadBalancerSourceRanges
          value: [NeedYourInput]
      - equal: 
          path: spec.ports.name
          value: [NeedYourInput]
      - equal: 
          path: spec.ports.port
          value: [NeedYourInput]
      - equal: 
          path: spec.ports.targetPort
          value: [NeedYourInput]
      - equal: 
          path: spec.selector.app
          value: [NeedYourInput]
      - equal: 
          path: spec.selector.release
          value: [NeedYourInput]
