suite: test kafka-chart/charts/cp-ksql-server/templates/ksql-queries-configmap.yaml
templates:
  - ksql-queries-configmap.yaml
tests:
  - it: should pass
    release:
      name: demo-release
    asserts:
      - equal: 
          path: apiVersion
          value: [NeedYourInput]
      - equal: 
          path: kind
          value: [NeedYourInput]
      - equal: 
          path: metadata.name
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.app
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.chart
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.release
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.heritage
          value: [NeedYourInput]
      - equal: 
          path: data
          value: [NeedYourInput]
