suite: test helloworld-chart/chart/templates/deployment.yaml
templates:
  - deployment.yaml
tests:
  - it: should pass
    release:
      name: demo-release
    asserts:
      - equal: 
          path: apiVersion
          value: [NeedYourInput]
      - equal: 
          path: kind
          value: [NeedYourInput]
      - equal: 
          path: metadata.name
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.app
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.chart
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.release
          value: [NeedYourInput]
      - equal: 
          path: metadata.labels.heritage
          value: [NeedYourInput]
      - equal: 
          path: spec.replicas
          value: [NeedYourInput]
      - equal: 
          path: spec.selector.matchLabels.app
          value: [NeedYourInput]
      - equal: 
          path: spec.selector.matchLabels.release
          value: [NeedYourInput]
      - equal: 
          path: spec.template.metadata.labels.app
          value: [NeedYourInput]
      - equal: 
          path: spec.template.metadata.labels.release
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.name
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.image
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.imagePullPolicy
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.command
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.ports.name
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.ports.containerPort
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.ports.protocol
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.livenessProbe.httpGet.path
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.livenessProbe.httpGet.port
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.readinessProbe.httpGet.path
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.readinessProbe.httpGet.port
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.containers.resources
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.nodeSelector
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.affinity
          value: [NeedYourInput]
      - equal: 
          path: spec.template.spec.tolerations
          value: [NeedYourInput]
